### ISSUE TITLE
Not Letting go of the keys in some cases

### ISSUE THREAD

**Issue by Sherknob** [Sherknob/PineDucky#2]
Resulting in i.e opening a bazillion terminals on target System. First discovered, when just executing
```
STRG ALT t
```

**Comment by L0v3P01s0n** [comment]
wait... what did STRG do again? I don't think that's a command

**Comment by Helmut-Becker** [comment]
Hello @L0v3P01s0n,
STRG is the CTRL key on the German layout. I am sorry, should've called it CTRL :)

**Comment by Helmut-Becker** [comment]
I will have a look later this day but I think, I have fixed the initial problem already and forgot to close the issue...
